name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        run: echo "cloning the code"

  build:
    needs: [code]
    runs-on: ubuntu-latest

    steps:
      - name: Build application
        run: echo "building the application"

  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Test the code
        run: echo "testing the app"

  deploy:
    needs: [test,build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the code
        run: echo "deploying the app"
