name: python-linter

on:
  push:
    branches:
      - main

jobs:
  python-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Public Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Linter
        run: pip install ruff

      - name: Check Python Files
        run: ruff .
