name: Schedule-Trigger

on:
  schedule:
    # Runs every day at 13:51 UTC
        - cron: '28 20 * * *'

jobs:
  run-workflow-at-midnight-ist:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning code
        uses: actions/checkout@v4

      - name: Workflow running
        run: echo "The workflow is running on the scheduled time."
